import type { Metadata } from "next";
import "./globals.css";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { theme } from "./theme";

export const metadata: Metadata = {
  title: "Kapol App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-full bg-gray-100 overflow-x-hidden`}>
        {/* <ThemeProvider theme={theme}>
          <CssBaseline /> */}
        {children}
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
